apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  description: ${{ values.description | dump }}
  tags:
    - java
    - spring-boot
    - backend
spec:
  type: service
  owner: ${{ values.owner | dump }}
  lifecycle: experimental
